services:
  - type: web
    name: disbot-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python web_server.py"
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false

  - type: worker
    name: disbot-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    autoDeploy: true
    envVars:
      - key: DISCORD_TOKEN
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
